# Generated by Django 5.0.7 on 2024-07-25 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RetreatDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Title of the retreat.', max_length=255, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the retreat.', null=True, verbose_name='Description')),
                ('location', models.CharField(blank=True, help_text='Location where the retreat takes place.', max_length=255, null=True, verbose_name='Location')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Cost of the retreat.', max_digits=10, null=True, verbose_name='Price')),
                ('retreat_type', models.CharField(blank=True, help_text='Type of the retreat (e.g., Signature, Standalone).', max_length=50, null=True, verbose_name='Type')),
                ('condition', models.CharField(blank=True, help_text='Condition or focus area of the retreat (e.g., Mental Wellness).', max_length=100, null=True, verbose_name='Condition')),
                ('image', models.URLField(blank=True, help_text='URL of the image representing the retreat.', null=True, verbose_name='Image')),
                ('tag', models.JSONField(blank=True, help_text='List of tags related to the retreat.', null=True, verbose_name='Tags')),
                ('duration', models.IntegerField(blank=True, help_text='Duration of the retreat in days.', null=True, verbose_name='Duration')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the retreat record was created.', verbose_name='Creation Date')),
            ],
            options={
                'verbose_name': 'Retreat Details',
                'verbose_name_plural': 'Retreats Details',
                'db_table': 'tb_retreat',
            },
        ),
        migrations.CreateModel(
            name='BookingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, help_text='ID of the user making the booking.', null=True, verbose_name='User ID')),
                ('user_name', models.CharField(blank=True, help_text='Name of the user making the booking.', max_length=255, null=True, verbose_name='User Name')),
                ('user_email', models.EmailField(blank=True, help_text='Email of the user making the booking.', max_length=254, null=True, verbose_name='User Email')),
                ('user_phone', models.CharField(blank=True, help_text='Phone number of the user making the booking.', max_length=20, null=True, verbose_name='User Phone')),
                ('payment_details', models.JSONField(blank=True, help_text='JSON data containing payment details.', null=True, verbose_name='Payment Details')),
                ('booking_date', models.DateField(blank=True, help_text='Date when the booking was made.', null=True, verbose_name='Booking Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the booking record was created.', verbose_name='Creation Date')),
                ('retreat', models.ForeignKey(blank=True, help_text='Retreat that is being booked.', null=True, on_delete=django.db.models.deletion.CASCADE, to='retreats_app.retreatdetails', verbose_name='Retreat')),
            ],
            options={
                'verbose_name': 'Booking Details',
                'verbose_name_plural': 'Bookings Details',
                'db_table': 'tb_booking',
                'unique_together': {('user_id', 'retreat', 'booking_date')},
            },
        ),
    ]
